apiVersion: v1
kind: Service
metadata:
  name: prometheus-export
  namespace: lens-metrics
spec:
  type: NodePort
  ports:
    - port: 9090
      name: http
      nodePort: 33000
      protocol: TCP
  selector:
    name: prometheus
