apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: lens-metrics
spec:
  type: NodePort
  ports:
    - port: 3000
      name: http
      nodePort: 32001
      protocol: TCP
  selector:
    app: task-manager-monitor
