apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
  namespace: prod
spec:
  selector:
    matchLabels:
      app: task-manager-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: task-manager-prod
    spec:
      containers:
        - name: task-manager-backend
          image: oburiatov/task-manager-backend-amd64:latest
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 3000
              hostPort: 3000
        - name: task-manager-frontend
          image: oburiatov/task-manager-frontend-amd64:latest
          imagePullPolicy: Always
          ports:
            - name: main
              containerPort: 443
              hostPort: 443
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: main
          # resources:
          #   requests:
          #     memory: "1Gi"
          #     cpu: "4000m"
          #   limits:
          #     memory: "2Gi"
          #     cpu: "6000m"
