apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
  namespace: prod
spec:
  selector:
    matchLabels:
      app: task-manager-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: task-manager-prod
    spec:
      containers:
        - name: task-manager-backend
          image: oburiatov/task-manager-backend-amd64:latest
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 30001
          volumeMounts:
            - name: secret-volume-back
              mountPath: /app/server/ssl/
        - name: task-manager-frontend
          image: oburiatov/task-manager-frontend-amd64:latest
          imagePullPolicy: Always
          ports:
            - name: https
              containerPort: 30000
          volumeMounts:
            - name: secret-volume-front
              mountPath: /etc/nginx/certs/
      volumes:
        - name: secret-volume
          secret:
            secretName: devopseek.me-cert
            namespace: prod