apiVersion: v1
kind: Service
metadata:
  name: task-manager
  namespace: prod
spec:
  type: NodePort
  ports:
    - name: main
      port: 443
      targetPort: 443
      nodePort: 443
  selector:
    app: task-manager-prod
