apiVersion: v1
kind: Service
metadata:
  name: task-manager-backend
  namespace: prod
spec:
  type: NodePort
  ports:
    - name: main
      port: 3001
      targetPort: 3001
      nodePort: 32700
  selector:
    app: task-manager-prod
