apiVersion: v1
kind: Service
metadata:
  name: task-manager
  namespace: prod
spec:
  type: NodePort
  ports:
    - name: https
      port: 30000
      targetPort: 30000
      nodePort: 30000
    - name: backend
      port: 30001
      targetPort: 30001
      nodePort: 30001
  selector:
    app: task-manager-prod
