apiVersion: v1
kind: Service
metadata:
  name: task-manager
  namespace: prod
spec:
  type: NodePort
  ports:
    - name: https
      port: 3001
      targetPort: 3001
      nodePort: 30005
      protocol: TCP
  selector:
    app: task-manager-prod
