apiVersion: v1
kind: Service
metadata:
  name: task-manager
  namespace: prod
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: task-manager-prod
