      apiVersion: v1
      kind: Secret
      metadata:
        name: pgsecret
        namespace: db-prod
      data:
        username: <base64_encoded_username>
        password: <base64_encoded_password>