apiVersion: v1
kind: Service
metadata:
  name: task-manager-db
  namespace: db-prod
spec:
  type: NodePort
  ports:
    - port: 5432
      name: db-port
      nodePort: 31000
      protocol: TCP
  selector:
    app: task-manager-prod