apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: stc-postgres-task-manager
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/no-provisioner 
volumeBindingMode: WaitForFirstConsumer 